---
title: "Visualizing COVID-19 with R"
output: html_notebook
---

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(tidyverse)

# Read datasets/confirmed_cases_worldwide.csv into confirmed_cases_worldwide
confirmed_cases_worldwide <- read_csv("confirmed_cases_worldwide.csv", col_types = cols(date = col_date(format = "%Y-%m-%d"), cum_cases = col_double()))

# See the result
confirmed_cases_worldwide
```

```{r}
# Draw a line plot of cumulative cases vs. date
# Label the y-axis
ggplot(confirmed_cases_worldwide, aes(x = date, y = cum_cases)) + geom_line() + ylab("Cumulative confirmed cases")
```

```{r}
# Read in datasets/confirmed_cases_china_vs_world.csv
confirmed_cases_china_vs_world <- read_csv("confirmed_cases_china_vs_world.csv",col_types = cols(date = col_date(format = "%Y-%m-%d"), 
                                  cum_cases = col_double()))

# See the result

glimpse(confirmed_cases_china_vs_world) 

# Draw a line plot of cumulative cases vs. date, colored by is_china
# Define aesthetics within the line geom
plt_cum_confirmed_cases_china_vs_world <- ggplot(confirmed_cases_china_vs_world) +
  geom_line(aes(x = date, y = cum_cases, color = is_china)) +
  ylab("Cumulative confirmed cases")

# See the plot
plt_cum_confirmed_cases_china_vs_world
```

```{r}

who_events <- tribble(
  ~ date, ~ event,
  "2020-01-30", "Global health\nemergency declared",
  "2020-03-11", "Pandemic\ndeclared",
  "2020-02-13", "China reporting\nchange"
) %>%
  mutate(date = as.Date(date))

# Using who_events, add vertical dashed lines with an xintercept at date
# and text at date, labeled by event, and at 100000 on the y-axis
plt_cum_confirmed_cases_china_vs_world + geom_vline(aes(xintercept = date), data = who_events, linetype = "dashed") + geom_text(aes(x = date, label = event), data = who_events, y = 100000)
```
```{r}
# Filter for China, from Feb 15
china_after_feb15 <- confirmed_cases_china_vs_world %>%  filter(is_china == "China", date >= "2020-02-15")


# Using china_after_feb15, draw a line plot cum_cases vs. date
# Add a smooth trend line using linear regression, no error bars
ggplot(china_after_feb15, aes(date, cum_cases)) + geom_line() + geom_smooth(method = 'lm', se = FALSE) + ylab("Cumulative confirmed cases")
```
```{r}
# Filter confirmed_cases_china_vs_world for not China
not_china <- confirmed_cases_china_vs_world %>% filter(is_china == "Not China")

# Using not_china, draw a line plot cum_cases vs. date
# Add a smooth trend line using linear regression, no error bars
plt_not_china_trend_lin <- ggplot(not_china, aes(date, cum_cases)) + geom_line() + geom_smooth(method = "lm", se = FALSE) + ylab("Cumulative confirmed cases")

# See the result
plt_not_china_trend_lin 
```
```{r}
# Modify the plot to use a logarithmic scale on the y-axis
plt_not_china_trend_lin + scale_y_log10()
```

```{r}
# Run this to get the data for each country
confirmed_cases_by_country <- read_csv("confirmed_cases_by_country.csv", col_types = cols(
                   country = col_character(),
                   province = col_character(),
                   date = col_date(format = "%Y-%m-%d"),
                   cases = col_double(),
                   cum_cases = col_double()
                 ))
glimpse(confirmed_cases_by_country)

# Group by country, summarize to calculate total cases, find the top 7
top_countries_by_total_cases <- confirmed_cases_by_country %>% group_by(country) %>% summarize(total_cases = max(cum_cases)) %>% top_n(7, total_cases)

# See the result
top_countries_by_total_cases
```
```{r}
# Read in the dataset from datasets/confirmed_cases_top7_outside_china.csv
confirmed_cases_top7_outside_china <- read_csv("confirmed_cases_top7_outside_china.csv", col_types = cols(
                   country = col_character(),
                   date = col_date(format = "%Y-%m-%d"),
                   cum_cases = col_double()
                 ))

# Glimpse at the contents of confirmed_cases_top7_outside_china
glimpse(confirmed_cases_top7_outside_china)

# Using confirmed_cases_top7_outside_china, draw a line plot of
# cum_cases vs. date, colored by country
ggplot(confirmed_cases_top7_outside_china, aes(x = date, y = cum_cases, color = country)) + geom_line() + ylab("Cumulative confirmed cases")
```

